![cover](cover/07.%20Concatenation%20and%20Split.png)

#### Outline
* Concatenate </br>
* Split </br>

#### Import Numpy

In [1]:
import numpy as np

#### Concatenate
Concatenate in NumPy means joining two or more arrays together into one bigger array.


In [5]:
a = np.arange(1, 5).reshape(2, 2)
a

array([[1, 2],
       [3, 4]])

In [6]:
b = np.arange(5, 9).reshape(2, 2)
b

array([[5, 6],
       [7, 8]])

In [8]:
## Concatenate by Columns
arr = np.concatenate((a, b), axis=0)
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
arr1 = np.vstack((a, b))
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [10]:
## Concatenate by Rows
arr3 = np.concatenate((a, b), axis=1)
arr3

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [11]:
arr4 = np.hstack((a, b))
arr4

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#### Split
Dividing an array into smaller parts


In [16]:
a = np.arange(1, 13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
np.split(a, 2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [19]:
np.split(a, 6)

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12])]

In [ ]:
np.split(a, 5)   # array split does not result in an equal division

ValueError: array split does not result in an equal division

### For Source code:
https://sites.google.com/view/aorbtech/programming/

#### @Aorb Tech