![cover](cover/09.%20Random%20Sampling.png)

#### Outline
* random.random()
* random.randint()
* np.random.seed()
* np.random.choice()
* np.random.permutation()

##### Import NumPy

In [1]:
import numpy as np

### Random Sampling
Random sampling means picking random items from a list, array, or range without any specific order.

#### random.random()

In [3]:
a = np.random.random(4)
a

array([0.65728899, 0.2552881 , 0.06392804, 0.43815529])

In [4]:
b = np.random.random(8)
b

array([0.11538031, 0.99215751, 0.15365112, 0.93983956, 0.95654005,
       0.82693807, 0.32414953, 0.63196981])

In [5]:
m = np.random.random((2, 3))
m

array([[0.3579339 , 0.13783759, 0.77857201],
       [0.90994759, 0.67231993, 0.34712862]])

In [6]:
m1 = np.random.random((5, 9))
m1

array([[0.98983757, 0.27272267, 0.74424754, 0.96730359, 0.70878169,
        0.03409971, 0.65188077, 0.28248959, 0.47498496],
       [0.25418996, 0.66159161, 0.38898409, 0.90171475, 0.93847643,
        0.71287685, 0.39837387, 0.23907748, 0.96919634],
       [0.9793644 , 0.23671987, 0.84610468, 0.71800144, 0.65069829,
        0.82642095, 0.56925184, 0.33859075, 0.19063601],
       [0.91713666, 0.72222415, 0.95520947, 0.0901057 , 0.2168561 ,
        0.96261562, 0.56438504, 0.3514087 , 0.48773383],
       [0.25009179, 0.6948415 , 0.56874738, 0.81966812, 0.00792193,
        0.33485861, 0.56532831, 0.08322405, 0.00456449]])

#### random.randint()

In [9]:
x = np.random.randint(1, 100)
x

72

In [10]:
yx = np.random.randint(7, 11)
yx

8

In [11]:
m2 = np.random.randint(1, 100, (3, 4))
m2

array([[34, 40, 31, 59],
       [88, 43, 86, 23],
       [19, 56, 40, 96]], dtype=int32)

In [12]:
m3 = np.random.randint(101, 120, (5, 5))
m3

array([[106, 103, 106, 106, 118],
       [113, 112, 101, 103, 119],
       [105, 107, 104, 107, 111],
       [107, 114, 114, 113, 106],
       [106, 107, 109, 105, 116]], dtype=int32)

### random.seed()

In [23]:
np.random.seed(0)
m4 = np.random.randint(4, 10)
m4

8

In [27]:
np.random.seed(0)
m4 = np.random.randint(4, 10)
m4

8

In [29]:
np.random.seed(42)
m5 = np.random.randint(4, 10)
m5

7

In [30]:
np.random.seed(42)
m6 = np.random.randint(4, 10)
m6

7

#### random.choice()

In [34]:
x = [1, 2, 3, 5, 7, 4, 9, 10]
np.random.choice(x)

np.int64(7)

In [35]:
x = [1, 2, 3, 5, 7, 4, 9, 10]
np.random.choice(x)

np.int64(9)

In [36]:
x = [1, 2, 3, 5, 7, 4, 9, 10]
np.random.choice(x)

np.int64(2)

In [37]:
x = [1, 2, 3, 5, 7, 4, 9, 10]
np.random.choice(x)

np.int64(3)

#### random.permutation()

In [38]:
x = [1, 4, 6, 7, 8]
np.random.permutation(x)

array([7, 4, 1, 8, 6])

In [39]:
x = [1, 4, 6, 7, 8]
np.random.permutation(x)

array([8, 7, 1, 4, 6])

In [40]:
x = [1, 4, 6, 7, 8]
np.random.permutation(x)

array([1, 6, 8, 4, 7])

### For Source code:
https://sites.google.com/view/aorbtech/programming/

#### @Aorb Tech