![cover](cover/02.%20N-Dimensional%20Arrays.png)

#### Outline
* Arrays
* Creating 1D Arrays
* Creating 2D Arrays

### Introduction to Arrays
* Arrays are much like a list, though they are not dynamic data structures, making them static. This means that arrays, unlike lists, cannot increase or decrease in length during runtime. They are mutable (changable during the runtime) and ordered.

##### Import NumPy

In [1]:
import numpy

#### Creating 1D Arrays
And checking their data-type, dimensionality, size and shape.

In [2]:
array = numpy.array([10, 122, 76, 28, 4])
print(array)

[ 10 122  76  28   4]


In [3]:
type(array)

numpy.ndarray

In [ ]:
array.ndim  # tells us the dimensionality of the array

1

In [ ]:
array.size  # tells us how many elements are stored in the array (works for 1-dimensional arrays)

5

In [ ]:
array.dtype # tells us the data type of the elements stored in the array

dtype('int64')

#### Creating 2D Arrays

In [ ]:
array_2d = numpy.array([[12, 13, 14],[15, 16, 17]]) # using nested brackets we can create 2-dimensional arrays
print(array_2d) # we can print the values in the array

[[12 13 14]
 [15 16 17]]


In [ ]:
array_2d.shape  # tells us the "shape" of the array, i.e. 2x3 grid of elements

(2, 3)

In [ ]:
type(array_2d)  # tells us the data type that the array_2d variable is

numpy.ndarray

In [ ]:
array_2d.dtype  # tells us the data type of the elements stored in the array

dtype('int64')

In [ ]:
array_2d.ndim   # tells us the dimensionality of the array

2

### For Source code:
https://sites.google.com/view/aorbtech/programming/

#### @Aorb Tech