![Cover](cover/03.%20Create%20Diff%20Metrics.png)

### Outline
* Create Ones Metrics 
* Create zeros Metrics 
* Create Empty metrics

#### Import Library

In [2]:
import numpy as np

#### Create a one mertrics

In [10]:
mx_ones = np.ones((3,5))     # default it's float
print(mx_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
mx_ones.dtype  

dtype('float64')

In [7]:
# define datatype
mx_ones = np.ones((3, 5), dtype = int)        # (shape(row, col), dtype)
print(mx_ones) 

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [8]:
mx_ones.dtype

dtype('int32')

#### Create a zeros mertrics

In [14]:
mx_zeros = np.zeros((3, 3), dtype = int) 
print(mx_zeros)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [15]:
mx_zeros = np.zeros((3, 3), dtype = bool) 
print(mx_zeros)

[[False False False]
 [False False False]
 [False False False]]


In [16]:
mx_zeros.dtype

dtype('bool')

#### Create a empty metrics


In [21]:
mx_empty = np.empty((3 ,4))
print(mx_empty)

[[1.04915343e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 2.08995303e-076 6.53597017e-042 1.39844679e-076]
 [1.50127648e-076 2.48522298e+184 2.72579194e-056 5.63692956e-062]]


In [22]:
mx_empty.dtype

dtype('float64')

### For Source Code:
https://sites.google.com/view/aorbtech/programming

### @Aorb Tech