![cover](cover/04.%20Functions.png)

#### Outline
* Arange
* Linspace
* Reshape
* Ravel
* Flatten
* Transpose

##### Import NumPy

In [1]:
import numpy

#### 4.1 arange
Creates an array in the range (a, b) with step size [n]: </br> `arange(a, b, n)` --> (start, stop, jump)

In [2]:
array = numpy.arange(1, 10, 2)  # create an array with odd numbers from 1-9
print(array)

[1 3 5 7 9]


In [3]:
array = numpy.arange(1, 101)    # create an array with numbers ranging from 1-100
print(array)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


#### 4.2 linspace
Creates a set of [n] values beetween [a] and [b]: </br>
`linspace(a, b, n)` --> (start, end, no_elements)

In [4]:
array = numpy.linspace(10, 100, 10) # create an array with 10 equally spaced elements between 10 and 100 (inclusive)
print(array)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [5]:
decimal = numpy.linspace(1, 3, 10)  # create an array with 10 equally spaced elements between 1 and 3 (inclusive)
print(decimal)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


#### 4.3 reshape
Rearranges the elements in the array to fit a new dimensionality, conforming to a given shape. </br>
i.e. distributing 12 elements into 2 arrays of size 6: (2, 6)</br>
`reshape(a, b, ... n)`

In [6]:
array = numpy.arange(1, 21) # create an array with 20 elements
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [7]:
array2 = array.reshape(4, 5)    # create a new array with the elements from our previous one
                                # such that the elements are rearranged to 4 arrays with 5 elements each
print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [8]:
array = numpy.arange(1, 28) # create an array with 27 elements
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


In [9]:
array3 = array.reshape(3, 3, 3) # create a new array with elements rearranged into a 3x3x3 matrix
print(array3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


#### 4.4 ravel
Reduces a multi-dimensional array into a 1D array. </br>
NOTE: Returns a view of the original array whenever possible. </br>
`ravel()`

In [10]:
print(array3.ravel())   # reduce the array from our previous example into a 1-dimensional array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


#### 4.5 flatten
Reduces a multi-dimensional array into a 1D array. </br>
NOTE: Always returns a copy of the original array. </br>
`flatten()`

In [11]:
print(array3.flatten()) # reduce the array from our previous example into a 1-dimensional array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


#### 4.6 transpose
Exchanges the rows and columns of elements in the array. </br>
Array[i, j] = Array[j, i] </br>
`transpose()`

In [12]:
matrix = numpy.arange(1,10).reshape(3,3)    # create a 3x3 matrix
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
transposed_matrix = matrix.transpose()  # transpose the elements in the matrix 
                                        # ( elements in position [i, j] are swapped with elements in position [j, i])
print(transposed_matrix)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### For Source code:
https://sites.google.com/view/aorbtech/programming/

#### @Aorb Tech