![Cover](cover/05.%20Operations.png)

### Outline
* Addition
* Subtract
* Division
* Multiplications
* Sum
* Mean
* Sqr
* Exp
* Log

#### Import Library

In [2]:
import numpy as np

### Mathematical Operations
NumPy allows us to do different math operations

In [12]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
b = np.arange(13, 25).reshape(3, 4)
b

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

### Addition

In [14]:
a + b

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [16]:
np.add(a, b)

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

### Subtract

In [17]:
np.subtract(a, b)

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

### Multiplications

In [19]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
b.T

array([[13, 17, 21],
       [14, 18, 22],
       [15, 19, 23],
       [16, 20, 24]])

In [18]:
np.multiply(a, b)

array([[ 13,  28,  45,  64],
       [ 85, 108, 133, 160],
       [189, 220, 253, 288]])

In [22]:
np.dot(a, b.T)

array([[150, 190, 230],
       [382, 486, 590],
       [614, 782, 950]])

### Division

In [26]:
np.divide(a, b)

array([[0.07692308, 0.14285714, 0.2       , 0.25      ],
       [0.29411765, 0.33333333, 0.36842105, 0.4       ],
       [0.42857143, 0.45454545, 0.47826087, 0.5       ]])

In [27]:
np.divide(b , a)

array([[13.        ,  7.        ,  5.        ,  4.        ],
       [ 3.4       ,  3.        ,  2.71428571,  2.5       ],
       [ 2.33333333,  2.2       ,  2.09090909,  2.        ]])

### Sum

In [28]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
np.sum(a)

np.int64(78)

### Mean

In [30]:
np.mean(a)  

np.float64(6.5)

### Sqr

In [31]:
np.square(a)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

### Sqrt

In [32]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

### Exp

In [34]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

### Log

In [ ]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

### Max

In [39]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
np.max(a)

np.int64(12)

### Min

In [41]:
np.min(a)

np.int64(1)

### For Source Code:
https://sites.google.com/view/aorbtech/programming

### @Aorb Tech