![cover](cover/06.%20Array%20Slicing.png)

#### Outline
* Row Slicing </br>
* Column Slicing </br>
* Diagonal Slicing </br>
* Item Size </br>

##### Import NumPy

In [1]:
import numpy

#### Row Slicing

`Array[start:end:step_size]`

In [2]:
array = numpy.arange(1, 11) # create our array
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
slice = array[0:5]          # access the first 5 elements of the array
print(slice)

[1 2 3 4 5]


In [4]:
slice_even = array[1::2]    # access every even element of the array (start from the second, skip every other element)
print(slice_even)

[ 2  4  6  8 10]


In [5]:
print(array[::-1])          # reverse the array (access every element, step backwards)

[10  9  8  7  6  5  4  3  2  1]


#### Column Slicing

`matrix[start:end:step_size, start:end:step_size]`

In [6]:
matrix = numpy.arange(1,26).reshape(5,5)    # create our matrix
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [7]:
print(matrix[0:,2])         # access the middle (in this case 3rd) column of our matrix

[ 3  8 13 18 23]


In [8]:
print(matrix[0:,1:4])       # access the center 3 columns of our matrix (in this case 2nd to 4th)

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


In [9]:
print(matrix[0:,::2])       # access every other element from the first

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


##### Row and Column Slicing

In [10]:
print(matrix[::2,1::2])     # access every even element from every other row

[[ 2  4]
 [12 14]
 [22 24]]


#### Diagonal Slicing
Format: </br>
`numpy.diag(matrix, k=n)` </br>
* n = 0 starts from first element [0, 0]
* n > 0 moves up
* n < 0 moves down

In [11]:
matrix = numpy.arange(1, 101).reshape(10,10)    # create our large matrix
print(matrix)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [12]:
print(numpy.diag(matrix, k=0))      # access the largest diagonal, from the first element

[  1  12  23  34  45  56  67  78  89 100]


In [13]:
print(numpy.diag(matrix, k=1))      # access the diagonal just above

[ 2 13 24 35 46 57 68 79 90]


In [14]:
print(numpy.diag(matrix, k=-1))     # access the diagonal just below

[11 22 33 44 55 66 77 88 99]


#### Item Size

In [15]:
matrix.itemsize                     # tells us the number of bytes each element of the array takes up

8

In [16]:
matrix.dtype                        # determine how many bits each elements take up by checking the data type

dtype('int64')

In [17]:
64/8                                # we can verify this information by dividing 64 (number of bits) by 8 (number of bits in a byte)

8.0

### For Source code:
https://sites.google.com/view/aorbtech/programming/

#### @Aorb Tech